### ISSUE TITLE
Error in running smallbaselineApp_hyp3.ipynb notebook

### ISSUE THREAD

**Issue by Rejoicet** [insarlab/MintPy-tutorial#32]
Hello Team,

I was attempting to do a SBAS analysis using the mintpy-hyp3 workflow. I downloaded my data in the required format using method shown in the video - [https://www.youtube.com/watch?v=R-t2utzo7mg]

I followed this by using cutGeotiffs.py script to clip the files according to the same dimension, which was successful.

I then started running the smallbaselineApp_hyp3.ipynb notebook where I am facing issues in the 3rd and 4th code cells. Below are the challenges that I am facing:

1. I ran the 4th cell (! smallbaselineApp.py --work-dir {work_dir}  {configName}) after skipping the 3rd cell because I assumed it was to be run only if I wanted to use the Ridgecrest dataset. While running the 4th cell I am getting the error - "re.error: incomplete escape \U at position 8". I have attached the complete error screenshot here
[error screenshot.pdf](https://github.com/insarlab/MintPy-tutorial/files/7190614/error.screenshot.pdf).
2. As part of debugging the error, I downloaded the Ridgecrest dataset (RidgecrestSenDT71.tar.xz) from [https://zenodo.org/record/5502403#.YUZLKrhKiUl] and looked at the directory structure. The hyp3 folder is similar to mine but the inputs folder in the mintpy folder has a file name "ERA5.h5" which is not present in mine, i.e. no ".h5" files in my mintpy folder. Is this ".h5" file needed for processing? If yes, could you please help me to understand how do I obtain it? Additionally, the notebook points to a  prep_ts_hyp3 script which I could not find anywhere either.

I would appreciate any help to progress from here.

Thank and Regards,
Rejoice

**Comment by yunjunz** [comment]
I guess @cirrusasf could better answer your first question.

As for the 2nd question, ERA5.h5 is not required for running. I prepared it manually for anonymous testing purposes only.

**Comment by Rejoicet** [comment]
Thank you @yunjunz for your response.

Hi @cirrusasf,

Could you please look into the first issue that I posted here. If there is any other additional information required, please feel free to let me know.


Regards,
Rejoice

**Comment by cirrusasf** [comment]
@Rejoicet Thank you for your interesting on our ASF hyp3 product. I am pleased to help you out. The first step I would like to know is if the configuration file is correct. Could you paste the configuration file? I also guess there are some possible issues. 1. is your mintpy environment update? 2. the cufGeotiffs.py may be out of data. I suggest you use following script to do it:

from osgeo import gdal
pattern = os.path.join(outdir, '**/*.tif')
files = glob.glob(pattern)

# determine the smallest area covered by all input files
corners = [gdal.Info(f, format='json')['cornerCoordinates'] for f in files]
ulx = max(corner['upperLeft'][0] for corner in corners)
uly = min(corner['upperLeft'][1] for corner in corners)
lrx = min(corner['lowerRight'][0] for corner in corners)
lry = max(corner['lowerRight'][1] for corner in corners)

# subset all input files to these common coordinates
for f in files:
    output_filename = f.replace('.tif', '_clip.tif')
    gdal.Translate(destName=output_filename, srcDS=f, projWin=[ulx, uly, lrx, lry])

Please let me your progress.

**Comment by Rejoicet** [comment]
Hello @cirrusasf,

When I used the code you shared for cutting the tif files, none of the files got cut. Trying to find a solution online, I found [](https://gdal.org/programs/gdal_translate.html) and [](https://gis.stackexchange.com/questions/306799/gdal-translate-projwin-giving-error-error-while-crease-subset-from-image) and from these links I updated the code as below:
`corners = [gdal.Info(f, format='json')['cornerCoordinates'] for f in files]
ulx = min(corner['upperLeft'][0] for corner in corners)
uly = max(corner['upperLeft'][1] for corner in corners)
lrx = max(corner['lowerRight'][0] for corner in corners)
lry = min(corner['lowerRight'][1] for corner in corners)`

Please let me know if this was a wrong way. Using this way, the files did get updated but then I came across the attached error:
[error screenshot2.pdf](https://github.com/insarlab/MintPy-tutorial/files/7221797/error.screenshot2.pdf). I am also attaching the config file here for your reference:
[Project2017.txt](https://github.com/insarlab/MintPy-tutorial/files/7221806/Project2017.txt)

If I was correct in updating the cutGeotiff code that you shared, then I am not sure how to progress from this error. I see two suggestions provided in the error but unfortunately I don't know how to apply those suggestions. Could you kindly provide some guidance? Please let me know if there is any more information that you'd need from me.

**Comment by cirrusasf** [comment]
The code I gave to you is getting the intersection of all files.  You should stick to the code I gave to you.  The code you posted here is just the opposite of what the cutoff doing. It gets the envelop of all files. If you use this, the application will end up trouble.  Your configuration file looks good. I guess your pairs are not correct, because they do not have overlap (intersection).  How do you choose the pairs list? Do you use vertex SBAS search type to get your  pairs list? You need manually add the pairs to make your whole list of pairs linked. Any broke will cause the analysis failure.  You can check your network of pairs in your mintpy sub-directory. The example network.pdf is here 
[network.pdf](https://github.com/insarlab/MintPy-tutorial/files/7227746/network.pdf)

**Comment by Rejoicet** [comment]
Hello @cirrusasf and @yunjunz,

The issue was that the pairs were not linked as @cirrusasf pointed out. After ensuring linkages, I was able to run the document completely and view the velocity and timeseries outputs.

However, for the timeseries output, it is blank as shown in this screenshot
[timeseries.pdf](https://github.com/insarlab/MintPy-tutorial/files/7229229/timeseries.pdf). Also I am unable to use the slider or the arrows to sort through the images. Could you please help me here? Please let me know if there is any other information that you might need from me.

**Comment by cirrusasf** [comment]
Did you use the notebook that we provided. Can you give me the notebook? The thing is you need make the matploylib support the movie mode. Just add the %matplotlib notebook in the same  cell as tsview command.  For example,
%matplotlib notebook
tsview.main(argv)

**Comment by Rejoicet** [comment]
Thank you @cirrusasf, for your help. Your suggestion worked.

![This](https://user-images.githubusercontent.com/42792268/136899812-0fbd2735-4172-473a-8e4f-ece67f033bcb.PNG) image is the output of the timeseries command. If I understand right, this date of 01/17/2021 is the reference image and the displacement maps for other dates are calculated based on how much they changed based on the 01/17/2021. If my understanding is right, then I would like to change that reference from 01/17/2021 image which is the 24th image to the 1st or 2nd image in the timeseries so that I am able to see displacement changes with respect to the initial image in the timeseries.

After looking online, I used "minty.reference.date" in the configuration file 
[SBAS_main_2020_2021.txt](https://github.com/insarlab/MintPy-tutorial/files/7327320/SBAS_main_2020_2021.txt) but it still did not work the way I expected it to. It still used reference of 01/17/2021. Please advice @cirrusasf @yunjunz 

Thanks in advance!

**Comment by yunjunz** [comment]
@Rejoicet For the reference date change to take effect, you need to re-run `smallbaselineAppp.py SBAS_main_2020_2021.txt`. Could you confirm that?
