### ISSUE TITLE
Creating interferograms using timeseries.h5

### ISSUE THREAD

**Issue by mohseniaref** [insarlab/MintPy-tutorial#52]
Hi,

I was wondering if it is possible to generate ifgramStack.h5 using timeseries.h5 in case of simulation according to the data that we have?
Could you kindly advise if this is achievable, and if so, provide any guidance or suggestions on the best approach to do so? 
Thank you in advance for your time and support.

Warm regards,
Mohammad

**Comment by yunjunz** [comment]
You could use [`ifgram_reconstruction.py`](https://github.com/insarlab/MintPy/blob/main/src/mintpy/legacy/ifgram_reconstruction.py) under the `legacy` directory. It should do exactly what you described.
